### PR TITLE
Some fixes for uploading code and running tests

### PR DESCRIPTION
**Pull request by multiplemonomials**
### Summary of changes 
This PR fixes some errors I ran into when doing some testing locally.

- Add detection of the configured baudrate for the test runner.  This means that, if your project is configured to a non-default stdio baudrate, greentea tests will now work properly
- Fix srst_config line in L452RE OpenOCD config file that seemed to prevent uploading on Linux.  On closer inspection, the `targets/stm32l4x.cfg` file already sets this setting.
- Add warning about old versions of stlink.  These versions do not take the same command line arguments as 1.7.0+, so you could get cryptic errors if one is installed and you try to use it.

#### Impact of changes 
 If your project is configured to a non-default stdio baudrate, greentea tests will now work properly

### Documentation 

----------------------------------------------------------------------------------------------------------------
### Pull request type 

    [] Patch update (Bug fix / Target update / Docs update / Test update / Refactor)
    [] Feature update (New feature / Functionality change / New API)
    [] Major update (Breaking change E.g. Return code change / API behaviour change)

----------------------------------------------------------------------------------------------------------------
### Test results 

- Confirmed that OpenOCD uploading now works on L452RE:
```
5: Open On-Chip Debugger 0.11.0
5: Licensed under GNU GPL v2
5: For bug reports, read
5: 	http://openocd.org/doc/doxygen/bugs.html
5: DEPRECATED! use 'adapter driver' not 'interface'
5: Info : The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
5: Info : clock speed 500 kHz
5: Info : STLINK V2J28M18 (API v2) VID:PID 0483:374B
5: Info : Target voltage: 3.240553
5: Info : stm32l4x.cpu: hardware has 6 breakpoints, 4 watchpoints
5: Info : starting gdb server for stm32l4x.cpu on 3333
5: Info : Listening on port 3333 for gdb connections
5: Info : Unable to match requested speed 500 kHz, using 480 kHz
5: Info : Unable to match requested speed 500 kHz, using 480 kHz
5: target halted due to debug-request, current mode: Thread 
5: xPSR: 0x01000000 pc: 0x08006610 msp: 0x10000698
5: ** Programming Started **
5: Info : device idcode = 0x20016462 (STM32L45/L46xx - Rev Y : 0x2001)
5: Info : flash size = 512kbytes
5: Info : flash mode : single-bank
5: Warn : Adding extra erase range, 0x0800ca30 .. 0x0800cfff
5: ** Programming Finished **
5: ** Resetting Target **
5: Info : Unable to match requested speed 500 kHz, using 480 kHz
5: Info : Unable to match requested speed 500 kHz, using 480 kHz
5: shutdown command invoked
```

- Confirmed that tests can now be run at 115100 baud via mbed_app.json setting.
 
    [] No Tests required for this change (E.g docs only update)
    [] Covered by existing mbed-os tests (Greentea or Unittest)
    [X] Tests / results supplied as part of this PR
    
    
----------------------------------------------------------------------------------------------------------------
### Reviewers 

@JohnK1987 

----------------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by JohnK1987** [comment]
Could be good to mentioned also wrong result before this change, because of an potential similar issue in the future. Just an idea.

I don't work on Linux so I have additional question about impact of this to other targets.
You cut out the setting for the hardware reset, if I understand correctly. Did you tried that also with F429ZI? 
I am asking because I set the default openOCD configs in targets what I did. 
https://github.com/mbed-ce/mbed-os/blob/ed4f4db159bff2758e4b4eb04a3acb0a0f0f6f11/targets/upload_method_cfg/NUCLEO_F767ZI.cmake#L38
https://github.com/mbed-ce/mbed-os/blob/ed4f4db159bff2758e4b4eb04a3acb0a0f0f6f11/targets/upload_method_cfg/NUCLEO_F446RE.cmake#L42

The rest looks good.

BR, Jan

**Comment by multiplemonomials** [comment]
> You cut out the setting for the hardware reset, if I understand correctly. Did you tried that also with F429ZI?

It was a while ago, but I think I got a random openocd config for F429ZI off some site, which seemed to work.  Then I copied it and made one for L452RE, which worked at first, but seemed to have issues when I tried it again last night.  I looked up the error message (don't have it on hand), and one of the solutions was to change the `srst_config` value, so I set that back to the default and thing seemed to work.  As you can probably see, I'm not an expert with OpenOCD configs, I just have to find what I can and muddle through 😅.

**Comment by multiplemonomials** [comment]
I guess, to answer your question, I haven't tried that with F429ZI.  If anyone gets any issues with what we have now, I'll give it a shot.

**Comment by multiplemonomials** [comment]
Tried the F429ZI.  I did see some weirdness initially, but it seems like it's a cabling problem on my end.  After wiggling the USB around for a while, it was able to work fine with the existing config file

**Comment by JohnK1987** [comment]
> As you can probably see, I'm not an expert with OpenOCD configs

I am too not :)

Ok, then we will see.

**Pull request merged**
