### PR TITLE
Remove unavailable and EOLed target boards - STM32

### PR DESCRIPTION
**Pull request by multiplemonomials**
### Summary of changes 

This PR removes various STMicro target boards that the targets.json5 scrub identified as being EoL and/or no longer manufactured.

As a reminder, boards must be sold to the general public to qualify for inclusion in Mbed CE as a target board.  If your board is not available to the general public, you are welcome to use Mbed on it, but please maintain it as a custom target outside of the Mbed CE source tree.

Also, because I almost forgot, this adds a new CI job to check if there are any entries in cmsis_mcu_descriptions.json5 that need to be added or removed when changes like this are made.

#### Impact of changes 
The following targets were removed:
- MTS_DRAGONFLY_F413RH
- WIO_3G
- WIO_BG96
- RHOMBIO_L476DMW1K
- ADV_WISE_1570
- MTS_DRAGONFLY_L496VG

The following components, which were only used by the removed targets, were also removed:
- COMPONENT_QUECTEL_EC2X
- COMPONENT_QUECTEL_BG96
- COMPONENT_QUECTEL_UG96
- COMPONENT_QUECTEL_BC95
- COMPONENT_QUECTEL_M26

#### Migration actions required 
If you use one of the removed targets, you will either need to migrate to a custom target, or propose to Mbed CE why this target should be re-added and the change from this PR reverted.

### Documentation 

None

----------------------------------------------------------------------------------------------------------------
### Pull request type 

    [] Patch update (Bug fix / Target update / Docs update / Test update / Refactor)
    [] Feature update (New feature / Functionality change / New API)
    [X] Major update (Breaking change E.g. Return code change / API behaviour change)

----------------------------------------------------------------------------------------------------------------
### Test results 

    [X] No Tests required for this change (E.g docs only update)
    [] Covered by existing mbed-os tests (Greentea or Unittest)
    [] Tests / results supplied as part of this PR
    
    
----------------------------------------------------------------------------------------------------------------
### Reviewers 

----------------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by multiplemonomials** [comment]
@JohnK1987 good to approve?

**Review by JohnK1987 — APPROVED** [review]

**Comment by multiplemonomials** [comment]
That's a good point.  I think that maybe the best approach would be to grab the Quectel BG96 source files and add them to a library in the libraries organization.

**Comment by JohnK1987** [comment]
@chrissnow please can you look on https://github.com/mbed-ce-libraries-examples/Quectel-Cellular-Driver

**Comment by chrissnow** [comment]
It compiles but It doesn't seem to end up linked
I have this is my mbedapp.json
```
    "target_overrides": {
        "*": {
 "QUECTEL_EC2X.provide-default": true,
"target.components_add":             ["QUECTEL_EC2X"],

```
provide-default doesn't seem to be being defined so this isn't being called.
CellularDevice *CellularDevice::get_default_instance() in QUECTEL_EC2X.cpp

Even if I define that myself it doesn't seem to override the weak symbol.
image


I don't think the library is getting any of the mbed.app defines.

image

However in mbed_config.cmake I do have.
```
    "MBED_CONF_QUECTEL_EC2X_TX=MDM_TX"
    "MBED_CONF_QUECTEL_EC2X_RX=MDM_RX"
    "MBED_CONF_QUECTEL_EC2X_RTS=MDM_RTS"
    "MBED_CONF_QUECTEL_EC2X_CTS=MDM_CTS"
    "MBED_CONF_QUECTEL_EC2X_PWR=MDM_PWR"
    "MBED_CONF_QUECTEL_EC2X_RST=MDM_RST"
    "MBED_CONF_QUECTEL_EC2X_BAUDRATE=115200"
    "MBED_CONF_QUECTEL_EC2X_START_TIMEOUT=15000"
    "MBED_CONF_QUECTEL_EC2X_PROVIDE_DEFAULT=1"
```

**Comment by multiplemonomials** [comment]
Hmm yeah, I do see some issues... I'm actually going to do some refactoring on this driver.  The biggest issue is, these `get_default_instance()` functions don't work too well because, if the library is compiled into a .a file, the linker won't correctly resolve weak symbols like these.

**Comment by multiplemonomials** [comment]
Ah, it looks like the JSON file wasn't being picked up because of the magic directory names (`COMPONENT_xxx`).  Frankly, those names are rather outdated and really aren't needed.  Plus, there's no real reason to require configuration through JSON with this library when we can just have people implement the onboard modem callback in their own code and sort out both problems at once.

I'm pushing a new version of the library, with just the EC2X setup changed for now.  Give it a try using the new instructions in the readme!

**Comment by chrissnow** [comment]
I will try and test it later or tomorrow.

My thoughts beyond making it work is that something that worked fine and simple no longer is..
The use of `get_default_instance()` does make writing examples easier.

I understand wanting to streamline the codebase but have always felt that a good variety of very common libraries should be usable out of the box.

Things that come to mind..

Modems
PCA9xxx port expanders
Esp32 at for WiFi

My dislike of the separate repo for every additional device is that it makes finding and adding them a chore.

Personally I would rather see  everything inside mbed-os or maybe a separate single single repo full of best effort drivers.

The Linux kernel is a good example of how drivers should be arranged and maintained.

**Comment by chrissnow** [comment]
Another thought here is that depending on the approach you take regarding driver's is that potentially manufacturers themselves  would consider writing good quality drivers in the hope that it brings revenue back due to uptake of their devices.

**Comment by multiplemonomials** [comment]
Hmm, that's a fair point.  While I still don't think this driver currently belongs as part of mbed-os, it could be cool to put together an "Mbed Community Drivers" repo that collects together lots of these drivers.  I will think about that, and frankly, if anyone is interested in doing that, I wouldn't stop them!  Though, to provide a counterpoint, the norm for Mbed OS has been to have lots of small repositories, each with one driver.  It was just that ARM Mbed had tooling (the mbed cli command) that made integrating them easier (for some workflows anyway).

**Comment by multiplemonomials** [comment]
Also, FWIW, Mbed OS actually *does* come with an ESP driver -- though it's for ESP8266, not ESP32.  You can check it out under `mbed-os/connectivity/drivers/wifi/COMPONENT_ESPRESSIF_ESP8266`.  I think it should be usable as a wifi driver for any board with that chip connected, by adding `COMPONENT_ESPRESSIF_ESP8266` to your json file.

**Comment by multiplemonomials** [comment]
By the way, something you should be aware of if you are using an STM32 target with a modem is https://github.com/mbed-ce/mbed-os/issues/205 .  This bug might cause data from the modem to be corrupted unless you explicitly disable sleep.

**Pull request merged**
