### PR TITLE
STM32F7 QSPI flash timeouts and 4-byte addressing

### PR DESCRIPTION
**Pull request by Jookia**
### Summary of changes 

On the STM32769NI the STM32 BSP has an issue where QSPI accesses timeout and require a chip reset. Mbed use to contain a patch to fix this similar to this one but the change was lost during an update.

Enable the workaround ST uses for specific F7 chips but on all chips. There's no downside to this from what I can tell.

The 4-byte addressing was disabled because of timeouts which I think are due to this issue but falsely misattributed to 4-byte addressing. Enable that again.

Further discussions:

https://github.com/ARMmbed/mbed-os/issues/10049
https://github.com/ARMmbed/mbed-os/issues/15108

https://github.com/STMicroelectronics/STM32CubeF7/issues/52
https://github.com/STMicroelectronics/STM32CubeF7/issues/82

### Documentation 

None

----------------------------------------------------------------------------------------------------------------
### Pull request type 

    [X] Patch update (Bug fix / Target update / Docs update / Test update / Refactor)
    [] Feature update (New feature / Functionality change / New API)
    [] Major update (Breaking change E.g. Return code change / API behaviour change)

----------------------------------------------------------------------------------------------------------------
### Test results 

I'm not sure how to make a test for this yet. The issue takes an hour to recreate.

### CODE REVIEW

**Comment by multiplemonomials** [comment]
Thanks for the patch!  Did you test this on hardware?

**Comment by Jookia** [comment]
Yes, I have tested this on hardware.

UNRELATED:

I did find another bug possibly related to the QSPI code: After flashing Zephyr
and playing with it, flashing stock Mbed could no longer do QSPI mode. The chip
would just crash. But Zephyr would work.

I spent a while trying to debug it and found that perhaps setting 4-byte
addressing first then enabling QSPI mode fixed it. This is the only difference
I saw when comparing Zephyr's code and setting it to do that in Mbed fixed
the chip. I can't reliably reproduce this bug or confirm that's the actual fix-
I was throwing things at the wall.

Should I do a PR for that too?

**Comment by multiplemonomials** [comment]
Awesome, in that case, I'll give it the green light!

Regarding the other issue... it's hard to say.  It would be good to fix that issue, but I don't want to merge a fix that hasn't been tested on other devices.  It's hard to know if it might break something else.  It's tough because we don't have any sort of CI setup that can test any of the devices with QSPI.

**Review by multiplemonomials — APPROVED** [review]

**Comment by Jookia** [comment]
Thanks for the merge! If the bug happens again I'll try and reproduce it proper and fix it for everyone. :)

**Comment by JohnK1987** [comment]
You change code inside ST's HALs what is copied into Mbed. How do we ensure that change will be mirrored into new version if it will be necessary to change it for a reason in future?

BR, Jan

**Comment by Jookia** [comment]
I don't know. Any ideas?

**Pull request merged**
