### PR TITLE
Upload: Support Nuvoton targets

### PR DESCRIPTION
**Pull request by ccli8**
### Summary of changes 

This supports upload method for Nuvoton targets, including:
 - NUMAKER_PFM_NANO130
- NUMAKER_PFM_NUC472
- NUMAKER_PFM_M453
- NUMAKER_PFM_M487
- NUMAKER_IOT_M487
- NUMAKER_IOT_M467
- NUMAKER_IOT_M252
- NUMAKER_IOT_M263A
- NU_M2354

----------------------------------------------------------------------------------------------------------------
### Pull request type 

    [X] Patch update (Bug fix / Target update / Docs update / Test update / Refactor)
    [] Feature update (New feature / Functionality change / New API)
    [] Major update (Breaking change E.g. Return code change / API behaviour change)

----------------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by multiplemonomials** [comment]
Thanks, this looks really clean!

Really only have one comment which is, I would love to have a way to detect whether the OpenOCD that CMake has found is the Nuvoton version and not the standard version.  Otherwise it would be all too easy to accidentally have the wrong one on your PATH.  Is there a specific version number that your OpenOCD builds report?

**Comment by ccli8** [comment]
Nuvoton customized openocd will fix version number to `0.10.022`. Hopefully it can be used to tell from standard:
```
$ openocd --version
Open On-Chip Debugger 0.10.022.0-dev-00493-gd6db465b-dirty (2023-12-14-15:04)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
```

**Comment by multiplemonomials** [comment]
Hmm, next step would be updating FindOpenOCD.cmake to check the version number.  I should be able to do that sometime within the next week.

**Comment by multiplemonomials** [comment]
Okay once #340 is merged, you should be able to add code like
```cmake
set(OPENOCD_VERSION_RANGE 0.10.022...0.10.22)
```

**Comment by multiplemonomials** [comment]
Also @ccli8 I have invited you to be a member of the mbed-ce organization on github!  Thanks for all your contributions!  This should give you access to non-protected branches on the main repository, let you edit the wiki, and let you review PRs.

**Comment by ccli8** [comment]
>  have invited you to be a member of the mbed-ce organization on github! Thanks for all your contributions! This should give you access to non-protected branches on the main repository, let you edit the wiki, and let you review PRs.

@multiplemonomials Thanks, we can make mbed-ce prominent and lasting.

**Comment by ccli8** [comment]
Following #340, added openocd version requirement (for Nuvoton fork version) into each config files:
```
set(OPENOCD_VERSION_RANGE 0.10.022...0.10.22)
```

**Review by multiplemonomials — APPROVED** [review]

**Pull request merged**
