### PR TITLE
Refactor upload methods to streamline the debugging experience

### PR DESCRIPTION
**Pull request by multiplemonomials**
### Summary of changes 

Over the last couple months, I've gotten a lot of feedback that debugging with Mbed CE in VS Code is a bit of a pain compared to other tools such as Mbed Studio.  And you guys are right: it's quite annoying to have to start the GDB server through a separate terminal, and have to run separate commands to load code.  Additionally, there's #77 : VS Code and J-Link GDB server can't be used together because the default GDB commands that VS Code runs are not understood by J-Link.

This PR attempts to fix both of these issues by refactoring the upload methods within Mbed CE, and redesigning the way that Mbed CE interacts with VS Code.

First of all, instead of creating targets within the upload method, upload methods now just set variables: `UPLOAD_GDBSERVER_DEBUG_COMMAND`, `UPLOAD_LAUNCH_COMMANDS`, etc.  These variables can be used by the IDE generators to output commands in the correct format.

Additionally, the VS Code generator has been made smarter.  It creates a tasks.json file containing one task, "GDB Server", which is filled in with the correct info to start the GDB server for the selected upload method.  Then, each of the launch configurations is configured to start this task in the background, so that the GDB server is run automatically.  Additionally, CMake now tracks the correct GDB command sequences for each GDB server, and fills those into the launch configuration for Cortex-Debug to use.  And last but not least, CMake runs the `load` command during debugger init, so the latest elf file is automatically flashed to the device when the debugger starts.  All this together means that you can now have a two-click debugging experience with VS Code: first build the target, then start the launch configuration, and then you're up and running!

Unfortunately, I still have not figured out a decent way to make VS Code build the CMake target before starting the debug session, so I can't make it truly one click.  If anyone knows a way to do that, let me know!

## TODO:
- Update J-Link and VS Code docs on wiki
- Update CLion generator to the new scheme

#### Impact of changes 
- Debugging experience in VS Code is much improved
- If a user has their own tasks.json file, it will get overwritten when they use Mbed CE
- Command-line debug targets (e.g. ninja debug-SomeApp) are no longer generated when using an IDE

### Documentation 

TODO

----------------------------------------------------------------------------------------------------------------
### Pull request type 

    [] Patch update (Bug fix / Target update / Docs update / Test update / Refactor)
    [] Feature update (New feature / Functionality change / New API)
    [X] Major update (Breaking change E.g. Return code change / API behaviour change)

----------------------------------------------------------------------------------------------------------------
### Test results 

    [] No Tests required for this change (E.g docs only update)
    [] Covered by existing mbed-os tests (Greentea or Unittest)
    [X] Tests / results supplied as part of this PR

I have tested:
- Command line with every GDB server other than redlink
- VS Code with every debugger other than redlink
and everything works as expected -- it drops you straight into a debug session and is stopped on main().

### CODE REVIEW

**Comment by JojoS62** [comment]
thanks for working on this subject. I will check it,
Is it still using the external gdbserver? I still prefer to use the cortex-debug serverypes. The external server is not well supported, it is too difficult for the developers the large number of variants.
The setup for a launch config in VSC is pretty easy, just add and select e.g. cortex-debug(stlink). VSC will add a template with the mandatory settings and for stlink you need only to set the .elf program.
Cortex-debug handles also the upload, change 'request' from attach to launch and thats it. My workflow is already build code (without flashing), then press run. With STLinkV3, debugging is working very fast.
So having a 'manual' upload method would be nice, in this mode the launch.json should not be touched.

**Comment by thegecko** [comment]
> I still have not figured out a decent way to make VS Code build the CMake target before starting the debug session

If the cmake build is exposed as a `TaskProvider` in VSCode, you can potentially use the [preLaunchTask](https://code.visualstudio.com/docs/editor/debugging) in the debug configuration to run a task first.

**Comment by multiplemonomials** [comment]
> If the cmake build is exposed as a TaskProvider in VSCode, you can potentially use the [preLaunchTask](https://code.visualstudio.com/docs/editor/debugging) in the debug configuration to run a task first.

Yeah that's actually what I did!  preLaunchTask is used to start the GDB server, so I can't also use it to run a build.

And even if preLaunchTask did support multiple tasks, that still wouldn't be enough, because I need to have it *wait* for the build task, but *not wait* for the GDB server to close before starting the debug session.  So I'd need something like `preLaunchTaskAsync` and `preLaunchTaskSync`.

**Comment by thegecko** [comment]
You can also chain tasks using 'dependsOn'.

If you need to launch gdb and friends, I recommend looking at the cdt-gdb-adapter:

https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter

We subclass this in mbed studio to start gdb and drive pyocd

**Comment by JojoS62** [comment]
debugging still does not start reliable. The first start was ok, now I get errors. The gdbserver is launched, but it looks like gdb is starting too fast and not waiting for the gdbserver. I can start the session only like before, starting the gdbserver task manually and then launch the debugger. I also have to uncomment the preLauchTask for gdbserver.

**Comment by multiplemonomials** [comment]
That's odd.  For me, it seems like VS Code is happy to wait 10 or 20 seconds after the launch configuration starts for the GDB server to come up.  What if you try on a different OS or machine? Also, if you don't start a GDB server at all, how long after you press run does it take before the "failed to connect to GDB server" message comes up?

**Comment by JojoS62** [comment]
I have been working with remote feature of VSC. target is connected to a Linux machine and I'm working on a windows PC. That works like I'm directly working on the Linux PC.
The Linux machine was running for some days, now I have rebooted it and starting the debugger via preLaunchTask works fine. So I think the problem was hanging gdbserver process.

The problem was that the gdbserver started (output in a terminal window ok), but no connecting attempt was seen. The timeout message from gdb came after 10...20 seconds, that is correct.

I see this PR as a good improvement and it should be merged. I can test later also with a JLink configuration.

**Comment by multiplemonomials** [comment]
OK!  Thanks to some advice above, I figured out how to use tasks.json to remove the requirement to build before debugging!  Now, each debug session will kick off a build task first, then wait until that build is done, then start the GDB server and begin the debug session.  Now, VS code debug sessions should be truly one-click!

**Comment by multiplemonomials** [comment]
@JojoS62 @JohnK1987 This should be ready for review now!

**Review by JohnK1987 — APPROVED** [review]

**Pull request merged**
