### PR TITLE
Custom upload method

### PR DESCRIPTION
**Pull request by lefebvresam**
### Summary of changes 

This fix allows the use of a custom configuration file which is specific for a custom target in the custom target folder. It enables the migration of custom targets together with their config, because for example programming methods are binded to specific targets. Prviously if you do the config in cmaketxt files you still get the message that a file has not been found. Evenmore this the place to define how your code is linked but not to do configuration.

### Documentation 

Update needed in documentation to make the user aware they can use that option.
----------------------------------------------------------------------------------------------------------------
### Pull request type 

    [] Patch update (Bug fix / Target update / Docs update / Test update / Refactor)
    [x] Feature update (New feature / Functionality change / New API)
    [] Major update (Breaking change E.g. Return code change / API behaviour change)

----------------------------------------------------------------------------------------------------------------
### Test results 

    [x] No Tests required for this change (E.g docs only update)
    [] Covered by existing mbed-os tests (Greentea or Unittest)
    [] Tests / results supplied as part of this PR
    
Has been tested locally.

### CODE REVIEW

**Comment by JohnK1987** [comment]
How I said before. From my point of view this is not compatible with designe of [Custom target example](https://github.com/mbed-ce/mbed-ce-custom-targets) and its structure but I agree with the idea about Upload method for custom targets.

Current state
```
./Project_Name/
│
├── mbed-os/
├── Build/
├── Custom_targets/
│   ├── YOUR_TARGET/
│   │	└──  somefiles.xxx
│   ├── ANOTHER_TARGET/
│   │	└──  somefiles.xxx
│   └──	CMakeLists.txt
│
├── CMakeLists.txt
├── mabed_app.json
├── custom_targets.json
└── main.cpp
```

@lefebvresam  solution (this PR) leads to project without custom_targets folder. So also the example should be reworked.
```
./Project_Name/
│
├── mbed-os/
├── Build/YOUR_TARGET/BuildProfile(
├── YOUR_TARGET/
│   ├──  somefiles.xxx (everything around target)
│   └──  YOUR_TARGET.cmake (upload config)
│
├── CMakeLists.txt
├── mabed_app.json
└── main.cpp
```

I believe it is very important to have a default well documented structure because of potential novices and especially when they have no experiences with Cmake.
But I also understand another requirements of someone else who know Cmake well.

So I propose something what can satisfy everyone. The default structure can look like below but it is still possible to set your own path in top lvl CmakeLists.txt before call of app.cmake via `CUSTOM_UPLOAD_CFG_PATH`

./Project_Name/
│
├── mbed-os/
├── Build/
├── Custom_targets/
│   ├── YOUR_TARGET/
│   │	├──  somefiles.xxx
│   │        └──  UploadMethod.cmake
│   ├── ANOTHER_TARGET/
│   │	├──  somefiles.xxx
│   │        └──  UploadMethod.cmake
│   │
│  ├── custom_targets.json
│  └──	CMakeLists.txt
│
├── CMakeLists.txt
├── mabed_app.json
└── main.cpp


```
# Load upload method configuration defaults for this target.
# Loading the settings here makes sure they are set at global scope, and also makes sure that
# the user can override them by changing variable values after including app.cmake.
#
# default expected paths
set(EXPECTED_CUSTOM_UPLOAD_CFG_FILE_PATH ${CMAKE_SOURCE_DIR}/custom_targets/${MBED_TARGET}/${MBED_TARGET}.cmake)
set(EXPECTED_MBED_UPLOAD_CFG_FILE_PATH ${CMAKE_SOURCE_DIR}/mbed-os/targets/upload_method_cfg/${MBED_TARGET}.cmake)

# check if a custom upload config path is defined in top lvl cmake
if((DEFINED CUSTOM_UPLOAD_CFG_PATH))
    if(EXISTS ${CUSTOM_UPLOAD_CFG_PATH})
        include(${CUSTOM_UPLOAD_CFG_PATH})
        message(STATUS "Mbed: Custom upload config included from ${CUSTOM_UPLOAD_CFG_PATH}")
    else()
        message(FATAL_ERROR "Mbed: Custom upload config is defined but files was not found here - ${CUSTOM_UPLOAD_CFG_PATH}")
    endif()
	
# check if a custom upload config is present in custom_targets/YOUR_TARGET folder
elseif(EXISTS ${EXPECTED_CUSTOM_UPLOAD_CFG_FILE_PATH})
	include(${EXPECTED_CUSTOM_UPLOAD_CFG_FILE_PATH})
	message(STATUS "Mbed: Custom upload config included from ${EXPECTED_CUSTOM_UPLOAD_CFG_FILE_PATH}")
	
# check for build in upload config
elseif(EXISTS ${EXPECTED_MBED_UPLOAD_CFG_FILE_PATH})
	include(${EXPECTED_MBED_UPLOAD_CFG_FILE_PATH})
	message(STATUS "Mbed: Loading default upload method configuration from ${EXPECTED_MBED_UPLOAD_CFG_FILE_PATH}")
else()
    message(STATUS "Mbed: Target does not have any upload method configuration.  'make flash-' commands will not be available unless configured by the upper-level project.")
    set(UPLOAD_METHOD_DEFAULT "NONE")
endif()
```
This is my opinion.

Also on the [forum was mentioned cool idea](https://forums.mbed.com/t/mbed-ce-debugging-custom-targets-in-vscode/22332/16) and is similar to my solution.

What do you think guys?

BR, Jan

**Comment by multiplemonomials** [comment]
I agree with @JohnK1987 about this!

**Comment by JohnK1987** [comment]
@lefebvresam will you continue or may I close this and create new one?

**Comment by lefebvresam** [comment]
Why it is required being able to set your own path in top lvl CmakeLists.txt? For the rest it looks like my solution: first check local, then global. But indeed I only use one target. This will be in most of the cases. You create software for one device. If you have another device you create a different project.

**Comment by JojoS62** [comment]
> Why it is required being able to set your own path in top lvl CmakeLists.txt?

The advantage is that you can keep custom_targets.json in the custorm_targets subdir and simply add it to a project by adding it as submodule. Moving this file to the root means changing the repo, copying is also not fine because you can make changes to the wrong file.


> You create software for one device. If you have another device you create a different project.

It is a real handy feature that you can compile the same code for another target by simply switching it in cmake, I love this feature. Also having multiple executables with one compilation of the mbed-os. A new project is always >1GB of space, even for a simple hello world test.

**Comment by JohnK1987** [comment]
There are many options how you can deal with it and what can happen. 
Every time come someone else who has its own idea about best solution and that is OK. So the possibility to set this in top level cmake is exactly for that.

I remember @JojoS62 had its own structure of projects- one MbedOS, one folder with multiple libs and custom_targets folder for multiple projects. Something like 

```
./MbedProjects/
│
├── mbed-os/
├── libraries/
│   ├── lib01/
│   │	├──  somefiles.xxx
│   │   └──  CMakeLists.txt
│   └── lib02/
│      	├──  somefiles.xxx
│       └──  CMakeLists.txt
├── Custom_targets/
│   ├── YOUR_TARGET/
│   │	├──  somefiles.xxx
│   │   └──  UploadMethod.cmake
│   ├── ANOTHER_TARGET/
│   │	├──  somefiles.xxx
│   │   └──  UploadMethod.cmake
│   │
│   ├── custom_targets.json
│   └──	CMakeLists.txt
├── Applications/
│   ├── Project1/
│   │   ├── Build/
│   │	├──  somefiles.xxx
│   │   └──  main.cpp
│   └── Project2/
│       ├── Build/
│      	├──  somefiles.xxx
│       └──   main.cpp
└──  CMakeLists.txt
```

For example you can release your product and after a time the MCU is unavailable or too expensive and you will want to use another one (different family or brand) for same purpose and same project. Normaly you need new project because of SDK but not with Mbed. So you can just add another target to the project and if the new MCu is not so far then you do not need change anthing else just target name for compilation. 
I use something similar in development of me ECU tester. I did some mistakes so i will make version2 of my board. In the project I have just macro BOARDVERSION and that will enable or disable changed parts of code. I know what I changed, I know where I can go back. No reason for new project.

**Comment by lefebvresam** [comment]
Ok I agree that you can deal with different HW revisions in the same project. Looks a nice feature but has to be documented very well and be consistent over all projects. I also like the idea that you just load a GIT project with all your target boards and just start to write a hello world for it.

**Comment by JojoS62** [comment]
> I remember @JojoS62 maybe had its own structure of projects- one MbedOS

yes, I used it in Mbed5, but Jamies solution with multiple executables in one project is smarter. It requires less compiling and less space.
Some major problem was the build system in Mbed5 that did a time consuming scan over the whole (large grown) lib directory. I feel better with having some repos with components and add them by 'git add submodule'

**Comment by JohnK1987** [comment]
I see no progress here so i created a new PR for this.

**Pull request closed without merging**
