### PR TITLE
Convert mbed-usb target, enable mbed-usb tests

### PR DESCRIPTION
**Pull request by multiplemonomials**
### Summary of changes 

- `mbed-usb` CMake target converted to a STATIC library to match other Mbed CE optional library CMake targets
- `mbed-usb-msd` split out from mbed-usb because it pulls in substantial additional dependencies
- All USB tests converted to CMake and reactivated.

Note: In mainline Mbed OS, USB tests were not run unless an additional config option (USB_DEVICE_TESTS) was supplied to the test runner.  This might mean that the tests don't pass for a lot of targets / are flaky 😬.  For now I've removed this option so they always run, we'll see what happens I guess.

#### Impact of changes 
Now that mbed-usb is a STATIC library target, it will only get built once instead of N times for N targets that use it.  Also, those using USBMSD.h will need to link the `mbed-usb-msd` library.

#### Migration actions required 
Those using USBMSD.h will need to link the `mbed-usb-msd` library.

### Documentation 

I'll add some notes to the wiki about USB tests.

----------------------------------------------------------------------------------------------------------------
### Pull request type 
    [] Patch update (Bug fix / Target update / Docs update / Test update / Refactor)
    [X] Feature update (New feature / Functionality change / New API)
    [] Major update (Breaking change E.g. Return code change / API behaviour change)

----------------------------------------------------------------------------------------------------------------
### Test results 

    [] No Tests required for this change (E.g docs only update)
    [] Covered by existing mbed-os tests (Greentea or Unittest)
    [X] Tests / results supplied as part of this PR

Will post CI tests below once I run them.
    
    
----------------------------------------------------------------------------------------------------------------
### Reviewers 

@JohnK1987 
@jay-sridharan 
----------------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by jay-sridharan** [comment]
Just curious.. is there a list somewhere of all the optional targets that can be linked in?

**Comment by multiplemonomials** [comment]
> Just curious.. is there a list somewhere of all the optional targets that can be linked in?

No, that's something I/we should really create.

**Comment by multiplemonomials** [comment]
I made some effort to debug the tests, and resolved a couple errors related to Linux permissions and Pyserial updates.  I compiled a full set of the needed udev rules at the bottom of the page [here](https://github.com/mbed-ce/mbed-os/wiki/Setting-up-a-Raspberry-Pi-as-a-Jenkins-Agent).  However, three of the four tests are still failing with things that look like "real" errors.  Either these errors always existed with STM32F4, or they got introduced by my CMake changes.  I don't know a whole lot about USB; I think we need someone who does to take a closer look.

## mbed-usb-device-basic
Gets halfway through, then fails with:
```
[1663456239.48][CONN][RXD] >>> Running case #9: 'endpoint test halt'...
[1663456239.53][CONN][INF] found KV pair in stream: {{__testcase_start;endpoint test halt}}, queued...
[1663456240.04][CONN][INF] found KV pair in stream: {{ep_test_halt;0123456789}}, queued...
interface 0, alt 0 -- skipping the default AlternateSetting
interface 0, alt 1 -- running tests
interface 0, alt 2 -- running tests
interface 0, alt 3 -- running tests
interface 0, alt 4 -- running tests
interface 0, alt 0 -- skipping the default AlternateSetting
interface 0, alt 1 -- running tests
[1663456240.52][HTST][INF] TEST FAILED: [/home/jenkins/workspace/mbed-os-ce/drivers/usb/tests/TESTS/host_tests/pyusb_basic.py]:1014, Unexpected error (USBError(32, 'Pipe error')).
[1663456240.53][SERI][TXD] {{fail;0}}
```
Looks like somehow one of the tests causes the Linux host to not be able to write to the USB device anymore in the middle of the test?

## mbed-usb-device-hid
Passes!

## mbed-usb-device-msd
Fails with:
```
[1663456291.11][CONN][RXD] >>> Running case #2: 'mount/unmount test - Heap block device'...
[1663456291.17][CONN][INF] found KV pair in stream: {{__testcase_start;mount/unmount test - Heap block device}}, queued...
[1663456292.25][CONN][INF] found KV pair in stream: {{check_if_mounted;0}}, queued...
[1663456318.47][HTST][INF] mount check failed !!!
[1663456318.48][SERI][TXD] {{failed;0}}
[1663456318.57][CONN][RXD] <greentea test suite>:303::FAIL: expected passed was failed (loop index: 1)
[1663456318.65][CONN][INF] found KV pair in stream: {{__testcase_finish;mount/unmount test - Heap block device;0;1}}, queued...
[1663456318.74][CONN][RXD] >>> 'mount/unmount test - Heap block device': 0 passed, 1 failed with reason 'Assertion Failed'
[1663456318.77][CONN][RXD] <greentea test suite>:0::PASS
```
Also, running `lsusb` after the test gets an infinite hang.  Safe to say the USB device is doing something bad.

## mbed-usb-device-serial
Gets halfway through, then fails with
```
[1663456332.04][CONN][RXD] >>> Running case #3: 'CDC RX single bytes concurrent'...
[1663456332.09][CONN][INF] found KV pair in stream: {{__testcase_start;CDC RX single bytes concurrent}}, queued...
[1663456332.17][CONN][INF] found KV pair in stream: {{send_single;0}}, queued...
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jenkins/workspace/mbed-os-ce/drivers/usb/tests/TESTS/host_tests/usb_device_serial.py", line 215, in send_data_sequence
    mbed_serial.reset_input_buffer()
  File "/home/jenkins/.local/lib/python3.9/site-packages/serial/serialposix.py", line 683, in reset_input_buffer
    self._reset_input_buffer()
  File "/home/jenkins/.local/lib/python3.9/site-packages/serial/serialposix.py", line 677, in _reset_input_buffer
    termios.tcflush(self.fd, termios.TCIFLUSH)
termios.error: (5, 'Input/output error')
```

I have also seen:
```
[1663454516.95][CONN][RXD] >>> Running case #3: 'CDC RX single bytes concurrent'...
[1663454517.01][CONN][INF] found KV pair in stream: {{__testcase_start;CDC RX single bytes concurrent}}, queued...
[1663454517.09][CONN][INF] found KV pair in stream: {{send_single;0}}, queued...
[1663454517.64][CONN][RXD] <greentea test suite>:423::FAIL: Expected 255 Was 94
[1663454517.69][HTST][INF] TEST ERROR: Write timeout
[1663454517.69][HTST][INF] __notify_complete(False)
[1663454517.69][HTST][INF] __exit_event_queue received
[1663454517.69][HTST][INF] test suite run finished after 5.80 sec...
```

I'd like to go ahead and merge this for now so that we can at least get partial USB support restored, then we can look at the errors later.  I'll try and get another board with USB added to the CI environment this week so we can test whether the results are the same on another board.

**Comment by multiplemonomials** [comment]
Looks like there is some evidence that these tests were already flaky:
- https://github.com/ARMmbed/mbed-os/issues/11912
- https://github.com/arduino/ArduinoCore-mbed/issues/129
- https://github.com/ARMmbed/mbed-os/issues/15129
- https://github.com/ARMmbed/mbed-os/issues/13215  (<---- direct cause of the basic test failing)

**Comment by JohnK1987** [comment]
> > Just curious.. is there a list somewhere of all the optional targets that can be linked in?
> 
> No, that's something I/we should really create.

There were a [handy tool](https://forums.mbed.com/t/finding-targets-with-features/10655/4?u=johnnyk)  :)
Of course that does not cover all targets where is USBDEVICE supported, but definitely it is good starting point.

Boards what I can test with USBDEVICE
* officially supported - H743ZI, F767ZI, F746NG, F469NI and F429ZI
* not market, but is also working - F446RE, L152RE (not sure about L432KC)

BR, Jan

**Comment by multiplemonomials** [comment]
I'm working on getting NRF52840 and LPC1768 testable with USB over the next few weeks.

**Comment by multiplemonomials** [comment]
Doing better when run on LPC1768, only the serial test fails:
```
4/4 Test #5: mbed-usb-device-serial ...........***Failed   66.55 sec

The following tests passed:
        mbed-usb-device-basic
        mbed-usb-device-hid
        mbed-usb-device-msd

75% tests passed, 1 tests failed out of 4
```
Same error as on the STM32

**Review by jay-sridharan — APPROVED** [review]
looks good!

**Pull request merged**
