### PR TITLE
add depth setting, json and html output to memap report

### PR DESCRIPTION
**Pull request by JojoS62**
### Summary of changes 

This PR is a feature upgrade to pass the depth of directory level to the memap.py. This allows a more detailed output of memory usage for compile units.
Memap.py has also the option to output a json file or a clickable html file.

### Documentation 

Set default is set to no json, no html and depth = 2. It can be overriden in the top level CMakeLists.txt e.g.:

```
set(MBED_MEMAP_DEPTH "4" )
set(MBED_MEMAP_CREATE_JSON TRUE)
set(MBED_MEMAP_CREATE_HTML TRUE)
```

The settings are cached and can be changed also by using the CMake cache editor.

----------------------------------------------------------------------------------------------------------------
### Pull request type 

    [] Patch update (Bug fix / Target update / Docs update / Test update / Refactor)
    [x] Feature update (New feature / Functionality change / New API)
    [] Major update (Breaking change E.g. Return code change / API behaviour change)

----------------------------------------------------------------------------------------------------------------
### Test results 

    [] No Tests required for this change (E.g docs only update)
    [] Covered by existing mbed-os tests (Greentea or Unittest)
    [] Tests / results supplied as part of this PR
    
    
----------------------------------------------------------------------------------------------------------------
### Reviewers 

@multiplemonomials 

----------------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by multiplemonomials** [comment]
Looks good, but could you add something to the wiki that mentions these options?  Up to you where to put it.

**Comment by JojoS62** [comment]
I have cloned the wiki by using https://github.com/mbed-ce/mbed-os.wiki.git as in the bottom of the page. But this has no content, only deleted file on stage.
Has it to be cloned into the mbed-ce directory?

**Comment by multiplemonomials** [comment]
You should just be able to edit the wiki on this repo, right?

**Comment by JojoS62** [comment]
yes, editing works. I tried to clone it to get a backup.

**Comment by multiplemonomials** [comment]
Wiki page created: https://github.com/mbed-ce/mbed-os/wiki/Mbed-CE-Build-System-Options

**Review by multiplemonomials — APPROVED** [review]
Nice, looks good!

**Pull request merged**
