### PR TITLE
Teensy 4.1 port with Ethernet support

### PR DESCRIPTION
**Pull request by multiplemonomials**
### Summary of changes 

This PR ports Mbed to run on the Teensy 4.1 board, including making use of the onboard Ethernet phy.  Also includes some other cleanups to the MIMXRT105x ethernet code in general, which was a bit of a mess.  Changes include:
- Move phy driver into connectivity/drivers/emac where it belongs
- Split phy driver into common functions (for all MIMXRT105x targets) and phy-specific functions for individual boards.
- Add new phy-specific functions for the DP83825 phy on the Teensy 4.1
- Fix incorrect autonegotiation logic in the MIMXRT105x Ethernet driver.  The old logic forced autonegotiation to restart after it completed the first time, and was equivalent to a this_thread::sleep_for(1s) after the ethernet cable was plugged in.
- Update a few places in FSL HAL to fix some compiler warnings
- Add PinNames.h for the Teensy 4.1, derived from the schematic.
- Add TEENSY_41 entry in targets.json

#### Impact of changes 

The Teensy 4.1 is now a supported target

### Documentation 

Will probably need to add a Teensy-specific board page at some point, but might hold off for upload method support.

----------------------------------------------------------------------------------------------------------------
### Pull request type 

    [] Patch update (Bug fix / Target update / Docs update / Test update / Refactor)
    [X] Feature update (New feature / Functionality change / New API)
    [] Major update (Breaking change E.g. Return code change / API behaviour change)

----------------------------------------------------------------------------------------------------------------
### Test results 

    [] No Tests required for this change (E.g docs only update)
    [] Covered by existing mbed-os tests (Greentea or Unittest)
    [X] Tests / results supplied as part of this PR
    
Board passed the UDP test suite:
```
{{__sync;0dad4a9d-59a3-4aec-810d-d5fb09d852c1}}
{{__version;1.3.0}}
{{__timeout;1200}}
{{__host_test_name;default_auto}}
[IMX EMAC] Link went up!  Negotiated for speed 100M, duplex full
{{__testcase_count;19}}
>>> Running 19 test cases...
{{__testcase_name;UDPSOCKET_OPEN_CLOSE_REPEAT}}
{{__testcase_name;UDPSOCKET_OPEN_LIMIT}}
{{__testcase_name;UDPSOCKET_RECV_TIMEOUT}}
{{__testcase_name;UDPSOCKET_SENDTO_TIMEOUT}}
{{__testcase_name;UDPSOCKET_OPEN_DESTRUCT}}
{{__testcase_name;UDPSOCKET_OPEN_TWICE}}
{{__testcase_name;UDPSOCKET_BIND_PORT}}
{{__testcase_name;UDPSOCKET_BIND_PORT_FAIL}}
{{__testcase_name;UDPSOCKET_BIND_ADDRESS_INVALID}}
{{__testcase_name;UDPSOCKET_BIND_ADDRESS}}
{{__testcase_name;UDPSOCKET_BIND_WRONG_TYPE}}
{{__testcase_name;UDPSOCKET_BIND_UNOPENED}}
{{__testcase_name;UDPSOCKET_ECHOTEST_NONBLOCK}}
{{__testcase_name;UDPSOCKET_ECHOTEST_NONBLOCK_CONNECT_SEND_RECV}}
{{__testcase_name;UDPSOCKET_ECHOTEST_BURST_NONBLOCK}}
{{__testcase_name;UDPSOCKET_SENDTO_REPEAT}}
{{__testcase_name;UDPSOCKET_ECHOTEST}}
{{__testcase_name;UDPSOCKET_ECHOTEST_CONNECT_SEND_RECV}}
{{__testcase_name;UDPSOCKET_ECHOTEST_BURST}}

>>> Running case #1: 'UDPSOCKET_OPEN_CLOSE_REPEAT'...
{{__testcase_start;UDPSOCKET_OPEN_CLOSE_REPEAT}}
{{__testcase_finish;UDPSOCKET_OPEN_CLOSE_REPEAT;1;0}}
>>> 'UDPSOCKET_OPEN_CLOSE_REPEAT': 1 passed, 0 failed
<greentea test suite>:0::PASS

>>> Running case #2: 'UDPSOCKET_OPEN_LIMIT'...
{{__testcase_start;UDPSOCKET_OPEN_LIMIT}}
{{__testcase_finish;UDPSOCKET_OPEN_LIMIT;1;0}}
>>> 'UDPSOCKET_OPEN_LIMIT': 1 passed, 0 failed
<greentea test suite>:0::PASS

>>> Running case #3: 'UDPSOCKET_RECV_TIMEOUT'...
{{__testcase_start;UDPSOCKET_RECV_TIMEOUT}}
{{__testcase_finish;UDPSOCKET_RECV_TIMEOUT;1;0}}
>>> 'UDPSOCKET_RECV_TIMEOUT': 1 passed, 0 failed
<greentea test suite>:0::PASS

>>> Running case #4: 'UDPSOCKET_SENDTO_TIMEOUT'...
{{__testcase_start;UDPSOCKET_SENDTO_TIMEOUT}}
{{__testcase_finish;UDPSOCKET_SENDTO_TIMEOUT;1;0}}
>>> 'UDPSOCKET_SENDTO_TIMEOUT': 1 passed, 0 failed
<greentea test suite>:0::PASS

>>> Running case #5: 'UDPSOCKET_OPEN_DESTRUCT'...
{{__testcase_start;UDPSOCKET_OPEN_DESTRUCT}}
{{__testcase_finish;UDPSOCKET_OPEN_DESTRUCT;1;0}}
>>> 'UDPSOCKET_OPEN_DESTRUCT': 1 passed, 0 failed
<greentea test suite>:0::PASS

>>> Running case #6: 'UDPSOCKET_OPEN_TWICE'...
{{__testcase_start;UDPSOCKET_OPEN_TWICE}}
{{__testcase_finish;UDPSOCKET_OPEN_TWICE;1;0}}
>>> 'UDPSOCKET_OPEN_TWICE': 1 passed, 0 failed
<greentea test suite>:0::PASS

>>> Running case #7: 'UDPSOCKET_BIND_PORT'...
{{__testcase_start;UDPSOCKET_BIND_PORT}}
{{__testcase_finish;UDPSOCKET_BIND_PORT;1;0}}
>>> 'UDPSOCKET_BIND_PORT': 1 passed, 0 failed
<greentea test suite>:0::PASS

>>> Running case #8: 'UDPSOCKET_BIND_PORT_FAIL'...
{{__testcase_start;UDPSOCKET_BIND_PORT_FAIL}}
{{__testcase_finish;UDPSOCKET_BIND_PORT_FAIL;1;0}}
>>> 'UDPSOCKET_BIND_PORT_FAIL': 1 passed, 0 failed
<greentea test suite>:0::PASS

>>> Running case #9: 'UDPSOCKET_BIND_ADDRESS_INVALID'...
{{__testcase_start;UDPSOCKET_BIND_ADDRESS_INVALID}}
{{__testcase_finish;UDPSOCKET_BIND_ADDRESS_INVALID;1;0}}
>>> 'UDPSOCKET_BIND_ADDRESS_INVALID': 1 passed, 0 failed
<greentea test suite>:0::PASS

>>> Running case #10: 'UDPSOCKET_BIND_ADDRESS'...
{{__testcase_start;UDPSOCKET_BIND_ADDRESS}}
{{__testcase_finish;UDPSOCKET_BIND_ADDRESS;1;0}}
>>> 'UDPSOCKET_BIND_ADDRESS': 1 passed, 0 failed
<greentea test suite>:0::PASS

>>> Running case #11: 'UDPSOCKET_BIND_WRONG_TYPE'...
{{__testcase_start;UDPSOCKET_BIND_WRONG_TYPE}}
{{__testcase_finish;UDPSOCKET_BIND_WRONG_TYPE;1;0}}
>>> 'UDPSOCKET_BIND_WRONG_TYPE': 1 passed, 0 failed
<greentea test suite>:0::PASS

>>> Running case #12: 'UDPSOCKET_BIND_UNOPENED'...
{{__testcase_start;UDPSOCKET_BIND_UNOPENED}}
{{__testcase_finish;UDPSOCKET_BIND_UNOPENED;1;0}}
>>> 'UDPSOCKET_BIND_UNOPENED': 1 passed, 0 failed
<greentea test suite>:0::PASS

>>> Running case #13: 'UDPSOCKET_ECHOTEST_NONBLOCK'...
{{__testcase_start;UDPSOCKET_ECHOTEST_NONBLOCK}}
{{__testcase_finish;UDPSOCKET_ECHOTEST_NONBLOCK;1;0}}
>>> 'UDPSOCKET_ECHOTEST_NONBLOCK': 1 passed, 0 failed
<greentea test suite>:0::PASS

>>> Running case #14: 'UDPSOCKET_ECHOTEST_NONBLOCK_CONNECT_SEND_RECV'...
{{__testcase_start;UDPSOCKET_ECHOTEST_NONBLOCK_CONNECT_SEND_RECV}}
{{__testcase_finish;UDPSOCKET_ECHOTEST_NONBLOCK_CONNECT_SEND_RECV;1;0}}
>>> 'UDPSOCKET_ECHOTEST_NONBLOCK_CONNECT_SEND_RECV': 1 passed, 0 failed
<greentea test suite>:0::PASS

>>> Running case #15: 'UDPSOCKET_ECHOTEST_BURST_NONBLOCK'...
{{__testcase_start;UDPSOCKET_ECHOTEST_BURST_NONBLOCK}}
{{__testcase_finish;UDPSOCKET_ECHOTEST_BURST_NONBLOCK;1;0}}
>>> 'UDPSOCKET_ECHOTEST_BURST_NONBLOCK': 1 passed, 0 failed
<greentea test suite>:0::PASS

>>> Running case #16: 'UDPSOCKET_SENDTO_REPEAT'...
{{__testcase_start;UDPSOCKET_SENDTO_REPEAT}}
{{__testcase_finish;UDPSOCKET_SENDTO_REPEAT;1;0}}
>>> 'UDPSOCKET_SENDTO_REPEAT': 1 passed, 0 failed
<greentea test suite>:0::PASS

>>> Running case #17: 'UDPSOCKET_ECHOTEST'...
{{__testcase_start;UDPSOCKET_ECHOTEST}}
{{__testcase_finish;UDPSOCKET_ECHOTEST;1;0}}
>>> 'UDPSOCKET_ECHOTEST': 1 passed, 0 failed
<greentea test suite>:0::PASS

>>> Running case #18: 'UDPSOCKET_ECHOTEST_CONNECT_SEND_RECV'...
{{__testcase_start;UDPSOCKET_ECHOTEST_CONNECT_SEND_RECV}}
{{__testcase_finish;UDPSOCKET_ECHOTEST_CONNECT_SEND_RECV;1;0}}
>>> 'UDPSOCKET_ECHOTEST_CONNECT_SEND_RECV': 1 passed, 0 failed
<greentea test suite>:0::PASS

>>> Running case #19: 'UDPSOCKET_ECHOTEST_BURST'...
{{__testcase_start;UDPSOCKET_ECHOTEST_BURST}}
{{__testcase_finish;UDPSOCKET_ECHOTEST_BURST;1;0}}
>>> 'UDPSOCKET_ECHOTEST_BURST': 1 passed, 0 failed
<greentea test suite>:0::PASS

>>> Test cases: 19 passed, 0 failed

-----------------------
0 Tests 0 Failures 0 Ignored
OK
{{__testcase_summary;19;0}}
{{end;success}}
{{__exit;0}}
```
    
----------------------------------------------------------------------------------------------------------------
### Reviewers 

----------------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by JojoS62** [comment]
Great! I think the passed tests are better than my review. I have just ordered the Ethernet kit for the board, that makes using ethernet easier.

**Comment by wwatson4506** [comment]
Reviewed and tested. No issues detected. Test results were the same as noted. Good work on the T41 target...

**Review by wwatson4506 — DISMISSED** [review]
Reviewed and tested...

**Comment by multiplemonomials** [comment]
@wwatson4506 Could you approve again?  Your approval got cleared because I added the MAC address change

**Review by wwatson4506 — APPROVED** [review]
Redo:)

**Comment by wwatson4506** [comment]
Reviewed and approved again...

**Pull request merged**
