### PR TITLE
Add disco f769 ni uploadcfg

### PR DESCRIPTION
**Pull request by JojoS62**
### Summary of changes 

Add upload configuration for DISCO_F769NI.

### Documentation 

----------------------------------------------------------------------------------------------------------------
### Pull request type 

    [x] Patch update (Bug fix / Target update / Docs update / Test update / Refactor)
    [] Feature update (New feature / Functionality change / New API)
    [] Major update (Breaking change E.g. Return code change / API behaviour change)

----------------------------------------------------------------------------------------------------------------
### Test results 

    [] No Tests required for this change (E.g docs only update)
    [] Covered by existing mbed-os tests (Greentea or Unittest)
    [] Tests / results supplied as part of this PR

Tested with JLINK
----------------------------------------------------------------------------------------------------------------
### Reviewers 

----------------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by JohnK1987** [comment]
Hello @JojoS62,

You wrote 

> Tested with JLINK

If you are not able to test the rest Upload methods, then set all methods to false. Also delete content of the Note 2. on the line 7. and replace it with information about the fact the other methods were not tested or something like that.

It makes sense?

BR, Jan

**Comment by JojoS62** [comment]
thanks for reviewing, it can check pyocd and stlink tomorrow.
I wanted also to remove the speed setting, as it is not neccessary for all configurations, but it is fixed required in the cmake. So how about to use a default speed that could be overriden if neccessary?

**Comment by JohnK1987** [comment]
Nice.

> I wanted also to remove the speed setting, as it is not neccessary for all configurations, but it is fixed required in the cmake. So how about to use a default speed that could be overriden if neccessary?

That sounds good.

So we could place here - https://github.com/mbed-ce/mbed-os/blob/7cd19915a2628436ab71cd4a893f7a51783e26bb/tools/cmake/upload_methods/UploadMethodPYOCD.cmake#L26 something like
```
set(PYOCD_CLOCK_SPEED_ARGS "123456")
if(NOT "${PYOCD_CLOCK_SPEED}" STREQUAL "")
	set(PYOCD_CLOCK_SPEED_ARGS  ${PYOCD_CLOCK_SPEED})
endif()
```

Instead of 123456 we place default frequency and on 36 and 55 we will replace PYOCD_CLOCK_SPEED with PYOCD_CLOCK_SPEED_ARGS.

Do you mean something like that?

BR, Jan

**Comment by JojoS62** [comment]
I have tested now also the other upload methods and they work also for this board.
With pyocd, I had only the effect that 'step over' performed a 'step into'.

About the clock speed: the debug configs should be reworked. Using the cortex-debug internal configurations works much better is more conveniant to use, the gdbserver doen't need to be started manually.

**Review by JohnK1987 — APPROVED** [review]

**Comment by JohnK1987** [comment]
Ok, maybe we can discuss about possible changes in our new section [Discussions](https://github.com/mbed-ce/mbed-os/discussions).

@multiplemonomials this one can be probably Merged.

BR, Jan

**Pull request merged**
